server:
  port: 8888

spring:
  datasource:
    username: root
    password: jing1111
    url: jdbc:mysql://127.0.0.1:3306/transaction?useUnicode=true&characterEncoding=UTF-8&userSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

mybatis:
  mapper-locations: classpath:Mapper/*.xml
  type-aliases-package: com.srx.transaction.Entities


logging:
  level:
    com: debug
    org.springframework: warn
